ALTER TABLE messages ADD COLUMN type VARCHAR(20) DEFAULT 'text';
ALTER TABLE messages ADD COLUMN file_path TEXT NULL;
ALTER TABLE messages ADD COLUMN seen_at DATETIME NULL;

ALTER TABLE users ADD COLUMN invitation_code VARCHAR(100) NULL;
ALTER TABLE users ADD COLUMN referred_by INT NULL;

CREATE TABLE IF NOT EXISTS story_elements (
  id INT AUTO_INCREMENT PRIMARY KEY,
  story_id INT NOT NULL,
  type VARCHAR(50) NOT NULL,
  content TEXT NULL,
  pos_x FLOAT DEFAULT 0,
  pos_y FLOAT DEFAULT 0,
  style JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_story_elements_story (story_id)
);
